"""empty message

Revision ID: 730014782f4e
Revises: 8b4e91acba2d
Create Date: 2025-10-02 09:16:22.906107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730014782f4e'
down_revision = '8b4e91acba2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antenna_pattern_points',
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('angle_deg', sa.Float(), nullable=False),
    sa.Column('amplitude_linear', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['antenna_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', 'angle_deg', name='uq_pattern_point')
    )
    with op.batch_alter_table('antenna_pattern_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_antenna_pattern_points_pattern_id'), ['pattern_id'], unique=False)
        batch_op.create_index('ix_pattern_point_order', ['pattern_id', 'angle_deg'], unique=False)

    op.create_table('project_antennas',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('antenna_id', sa.UUID(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('spacing_m', sa.Float(), nullable=False),
    sa.Column('phase_deg', sa.Float(), nullable=False),
    sa.Column('amplitude_linear', sa.Float(), nullable=False),
    sa.Column('tilt_deg', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['antenna_id'], ['antennas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'position_index', name='uq_project_slot')
    )
    with op.batch_alter_table('project_antennas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_antennas_antenna_id'), ['antenna_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_antennas_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('antenna_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('angles_deg')
        batch_op.drop_column('amplitudes_linear')

    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_assistant_conversation_user'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('projects_antenna_id_fkey'), type_='foreignkey')
        batch_op.drop_column('antenna_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('projects_antenna_id_fkey'), 'antennas', ['antenna_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_assistant_conversation_user'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('antenna_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amplitudes_linear', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('angles_deg', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('project_antennas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_antennas_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_antennas_antenna_id'))

    op.drop_table('project_antennas')
    with op.batch_alter_table('antenna_pattern_points', schema=None) as batch_op:
        batch_op.drop_index('ix_pattern_point_order')
        batch_op.drop_index(batch_op.f('ix_antenna_pattern_points_pattern_id'))

    op.drop_table('antenna_pattern_points')
    # ### end Alembic commands ###
