from __future__ import annotations

CATALOG_CATEGORIES = [
    {
        "id": "conversion-calculators",
        "title": "All Conversion Calculators",
        "items": [
            "dBm To Watt Calculator",
            "Watt To dBm Calculator",
            "Frequency to Wavelength Calculator",
            "Wavelength to Frequency Calculator",
            "Hz to PPM Calculator",
            "Noise Figure to Noise Temperature Converter",
            "Power Unit Conversion Calculator",
            "SINAD to ENOB Calculator",
            "dBµV to dBm Calculator",
            "dBm to dBµV Calculator",
            "dBm to dBmV Calculator",
            "dBm to dBW Conversion Calculator",
            "dBm to Vrms Calculator",
            "dBmV to dBm Calculator",
            "dBW to dBm Conversion Calculator",
            "Milliwatt to Watt Calculator",
            "Noise Factor to Noise Figure Calculator",
            "Noise Figure to Noise Factor Calculator",
            "Noise Temperature to Noise Figure Converter",
            "PPM to Hz Calculator",
            "RF Phase Noise to Phase Jitter Converter Calculator",
            "RF Power Ratio Conversion Calculator",
            "Vrms to dBm Calculator",
            "Watt to Milliwatt Calculator",
        ],
    },
    {
        "id": "antenna-calculators",
        "title": "Antenna Calculators",
        "items": [
            "Antenna Downtilt Angle Calculator",
            "Antenna Downtilt Coverage Radius Calculator",
            "Antenna Near/Far Field Calculator",
            "Antenna Power Density Calculator",
            "Dipole Antenna Length Calculator",
            "Helical Antenna Design Calculator",
            "Line of Sight Calculator",
            "Microstrip Patch Antenna Calculator",
            "Parabolic Reflector Antenna Calculator",
            "Parabolic Reflector Antenna Gain Calculator",
            "Whip Antenna Calculator",
        ],
    },
    {
        "id": "attenuator-calculators",
        "title": "Attenuator Calculators",
        "items": [
            "Balanced Attenuator Calculator",
            "Bridged Tee Attenuator Calculator",
            "Pi Attenuator Calculator",
            "Reflection Attenuator Calculator",
            "RF Attenuator Calculators",
            "Tee Attenuator Calculator",
        ],
    },
    {
        "id": "microstrip-calculators",
        "title": "Microstrip Calculators",
        "items": [
            "Differential Microstrip Impedance Calculator",
            "Differential Microstrip Impedance Calculator (Using Zo)",
            "Embedded Microstrip Impedance Calculator",
            "Microstrip Impedance Calculator",
            "Microstrip Mitred Bend Calculator",
            "Microstrip Width Calculator",
        ],
    },
    {
        "id": "radar-calculators",
        "title": "Radar Calculators",
        "items": [
            "Effective Antenna Aperture Calculator",
            "Maximum Unambiguous Range Calculator",
            "PRF Calculator",
            "Radar Blind Speed Calculator",
            "Radar Range Calculator",
            "Target Gain Factor Calculator",
        ],
    },
    {
        "id": "rf-calculators",
        "title": "RF Calculators",
        "items": [
            "EIRP Calculator",
            "Link Budget Calculator",
            "Coaxial Cable Impedance Calculator",
            "N-Way Power Divider Calculator",
            "Wilkinson Power Divider Calculator",
            "Cascaded Noise Figure Calculator",
            "Coaxial Cable Cutoff Frequency Calculator",
            "CRA Calculator",
            "Delta ↔ Wye Conversion Calculator",
            "Directional Coupler Calculator",
            "Free Space Path Loss Calculator",
            "Fresnel Zone Calculator",
            "Friis Transmission Calculator",
            "Gain Uncertainty due to Mismatch Calculator",
            "Inductor Q Factor Calculator",
            "IRA Calculator",
            "Microstrip Calculator",
            "Microwave Band Pass Filter Calculator",
            "Minimum Detectable Signal Calculator",
            "Plane Wave Calculator",
            "Power Added Efficiency (PAE) Calculator",
            "Quarter Wave Transformer Impedance Calculator",
            "Quartz Crystal Parameter Calculator",
            "Reflex Klystron Calculator",
            "Resonant Frequency Calculator",
            "RF Transformer Calculator",
            "Skin Depth Calculator",
            "Slot Line Calculator",
            "SAR Calculator",
            "Spurious Free Dynamic Range Calculator",
            "Thermal Noise Power Calculator",
            "TDR Length Calculator",
            "Varactor Diode Calculator",
            "Wye to Delta Conversion Calculator",
        ],
    },
    {
        "id": "vswr-calculators",
        "title": "VSWR, Return Loss and Reflection Coefficient Calculators",
        "items": [
            "Forward/Reflected Power to VSWR Calculator",
            "Reflection Coefficient Calculator",
            "Reflection Coefficient to Return Loss Calculator",
            "Reflection Coefficient to VSWR Calculator",
            "Return Loss to Reflection Coefficient Calculator",
            "Return Loss to VSWR Calculator",
            "VSWR Calculator",
            "VSWR to Reflection Coefficient Calculator",
            "VSWR to Return Loss Calculator",
        ],
    },
    {
        "id": "waveguide-calculators",
        "title": "Waveguide Calculators",
        "items": [
            "Cavity Resonance Frequency Calculator",
            "Circular Waveguide Calculator",
            "Conical Horn Antenna Gain Calculator",
            "Rectangular Waveguide Cut-off Frequency Calculator",
            "Rectangular Waveguide Wavelength Calculator",
            "Wavelength Calculator (TEM)",
        ],
    },
]
